config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
  get '/about', to: 'pages#about', as: :about
  get '/readnext', to: 'pages#readnext', as: :read_next

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

def complete
  if @book.completed == false
    return "Incomplete"
  else
    return "Complete"
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
class AuthorController < ApplicationController
before_action :set_author, only: [:create, :show]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  end


private

def set_author
  @author = Author.find(params[:id])
end

def author_params
  params.require(:author).permit(:name)
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @book.completed == true
      redirect_to book_path(@book)
    else
      @book.update(book_params)
      redirect_to book_path(@book)
    end
  end

  def search
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :note, :completed)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def readnext
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/new.html.erb
<div class="container">
<h1> Add Book </h1>
 <%= simple_form_for @author do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>
<%=link_to "Cancel", books_path, class: "btn btn-primary" %>
</div>

app/views/books/edit.html.erb
<div class="container">


<h1> Edit Book </h1>
 <%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :note %>
  <%= f.input :completed %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<%=link_to "Back", root_path, class: "btn btn-primary"%>
<% end %>
</div>

app/views/books/index.html.erb
<div class= "container m-10">
  <div class ="col-12">

<div class="container">
  <h4 style="margin-top: 50px; margin-left: 30px;">Carmen's</h4>
      <h1 style= "margin-left: 30px">Book Repository</h1>
      </div>
<div class="row text-center">


<%@books.each do |book|%>

<div data-aos="fade-up"
data-aos-offset="200"
    data-aos-delay="50"
    data-aos-duration="1000"
>

  <div class="container-fluid">
<div class="card p-2 m-5" style="width: 15rem; background-image: linear-gradient(to top, #abb7a8, #b7c7af, #c5d6b5, #d5e6ba, #e7f5be);">
  <div class="card-header" style="background-color: rgb(255, 254, 244)">
    <strong><%= book.completed? ? "COMPLETE" : "INCOMPLETE" %></strong>
  </div>
  <img class="card-img-top" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="Card image cap">
  <div class="card-body" style="background-color: rgb(255, 255, 255);">
  <h5 class="card-title"><%= link_to book.title, book_path(book)%></h5>
  <h6 class="card-subtitle mb-2 text-muted">  <%=book.author%></h6>
    <p class="card-text">
     </p>
    <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary"%>
    <%=link_to book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-bomb" do%>
         <i class="far fa-trash-alt"></i>
      <%end%>
    </div>
  </div>
</div>
      </div>

<%end%>
</div>
<div class="container">
        <div class="col-12">
  <div class="row-text-center">
<%= link_to "Add a book", new_book_path, class: "btn btn-primary m-3" %>
</div>
</div>
</div>

</div>



</div>

app/views/books/new.html.erb
<div class="container">
<h1> Add Book </h1>
 <%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :note %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<%=link_to "Cancel", books_path, class: "btn btn-primary" %>
<% end %>

</div>

app/views/books/show.html.erb
<div class="container">
<h1><%=@book.title%></h1>

<h4>Author</h4>
<p><%=@book.author%></p>

<h4> Notes </h4>
<p><%=@book.note%></p>

<%=link_to "Back", root_path, class: "btn btn-primary"%>

<%=link_to "Edit", edit_book_path, class: "btn btn-primary"%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Daimon Shrine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="animate.min.css">

     <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

    <script src="https://kit.fontawesome.com/1c2bb2457d.js"></script>
  </head>

  <body>
<style>
        body{
            background-color: #16172e;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 1000'%3E%3Cg %3E%3Ccircle fill='%2316172e' cx='50' cy='0' r='50'/%3E%3Cg fill='%231d1b36' %3E%3Ccircle cx='0' cy='50' r='50'/%3E%3Ccircle cx='100' cy='50' r='50'/%3E%3C/g%3E%3Ccircle fill='%23261e3e' cx='50' cy='100' r='50'/%3E%3Cg fill='%232f2146' %3E%3Ccircle cx='0' cy='150' r='50'/%3E%3Ccircle cx='100' cy='150' r='50'/%3E%3C/g%3E%3Ccircle fill='%2339234d' cx='50' cy='200' r='50'/%3E%3Cg fill='%23442554' %3E%3Ccircle cx='0' cy='250' r='50'/%3E%3Ccircle cx='100' cy='250' r='50'/%3E%3C/g%3E%3Ccircle fill='%23502759' cx='50' cy='300' r='50'/%3E%3Cg fill='%235d295f' %3E%3Ccircle cx='0' cy='350' r='50'/%3E%3Ccircle cx='100' cy='350' r='50'/%3E%3C/g%3E%3Ccircle fill='%23692963' cx='50' cy='400' r='50'/%3E%3Cg fill='%23762a67' %3E%3Ccircle cx='0' cy='450' r='50'/%3E%3Ccircle cx='100' cy='450' r='50'/%3E%3C/g%3E%3Ccircle fill='%23842a69' cx='50' cy='500' r='50'/%3E%3Cg fill='%23912a6b' %3E%3Ccircle cx='0' cy='550' r='50'/%3E%3Ccircle cx='100' cy='550' r='50'/%3E%3C/g%3E%3Ccircle fill='%239f296c' cx='50' cy='600' r='50'/%3E%3Cg fill='%23ac296c' %3E%3Ccircle cx='0' cy='650' r='50'/%3E%3Ccircle cx='100' cy='650' r='50'/%3E%3C/g%3E%3Ccircle fill='%23b9296c' cx='50' cy='700' r='50'/%3E%3Cg fill='%23c6296a' %3E%3Ccircle cx='0' cy='750' r='50'/%3E%3Ccircle cx='100' cy='750' r='50'/%3E%3C/g%3E%3Ccircle fill='%23d32b67' cx='50' cy='800' r='50'/%3E%3Cg fill='%23df2d64' %3E%3Ccircle cx='0' cy='850' r='50'/%3E%3Ccircle cx='100' cy='850' r='50'/%3E%3C/g%3E%3Ccircle fill='%23ea3160' cx='50' cy='900' r='50'/%3E%3Cg fill='%23f5365b' %3E%3Ccircle cx='0' cy='950' r='50'/%3E%3Ccircle cx='100' cy='950' r='50'/%3E%3C/g%3E%3Ccircle fill='%23ff3d55' cx='50' cy='1000' r='50'/%3E%3C/g%3E%3C/svg%3E");
background-attachment: fixed;
background-size: contain;
        }
    </style>


<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" style= "margin-top: 8px;">
        <%=link_to about_path do%>About<%end%>
      </li>
          <li class="nav-item">
        <a class="nav-link" href="#">Reading List</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <%= yield %>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
    AOS.init({
  // Global settings:
  disable: false, // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
  startEvent: 'DOMContentLoaded', // name of the event dispatched on the document, that AOS should initialize on
  initClassName: 'aos-init', // class applied after initialization
  animatedClassName: 'aos-animate', // class applied on animation
  useClassNames: false, // if true, will add content of `data-aos` as classes on scroll
  disableMutationObserver: false, // disables automatic mutations' detections (advanced)
  debounceDelay: 50, // the delay on debounce used while resizing window (advanced)
  throttleDelay: 99, // the delay on throttle used while scrolling the page (advanced)


  // Settings that can be overridden on per-element basis, by `data-aos-*` attributes:
  offset: 120, // offset (in px) from the original trigger point
  delay: 0, // values from 0 to 3000, with step 50ms
  duration: 400, // values from 0 to 3000, with step 50ms
  easing: 'ease', // default easing for AOS animations
  once: false, // whether animation should happen only once - while scrolling down
  mirror: false, // whether elements should animate out while scrolling past them
  anchorPlacement: 'top-bottom', // defines which position of the element regarding to window should trigger the animation

});
  </script>
  </body>
</html>

app/views/pages/about.html.erb
<div class= "container">
<h1>About</h1>
<p>The Greek words daimon and daimonion express a determining power which comes upon man from outside, like providence or fate, though the ethical decision is left to man. He must know, however, what he is deciding about and what he is doing. Then, if he obeys he is following not just his own opinion, and if he rejects he is destroying not just his own invention <br>~Carl Jung, CW 9ii, Para 51</p>

<%=link_to "Back", root_path, class: "btn btn-primary"%>
</div>